[env:lasec-rc_16]
build_type = debug
platform = espressif32@^7.0.1
board = lasec-rc_16
board_build.partitions = app.csv
board_build.filesystem = spiffs
framework = espidf
monitor_filters = esp32_exception_decoder
extra_scripts = tools/generate_audio_pack.py
lib_deps = 
;	bodmer/TFT_eSPI@^2.4.32
;build_flags =
;	-Os
;	-DCORE_DEBUG_LEVEL=1 ; 0= none, 1= error, 2= warn, 3= info, 4= debug, 5= verbose
;	-include include/board_config.h
;	-DUSER_SETUP_LOADED=1
;	-DST7735_DRIVER=1
;	-DTFT_WIDTH=80
;	-DTFT_HEIGHT=160
;	-DST7735_REDTAB160x80=1
;	-DTFT_RGB_ORDER=TFT_BGR
;	-DTFT_MISO=-1
;	-DTFT_MOSI=PIN_LCD_MOSI
;	-DTFT_SCLK=PIN_LCD_SCLK
;	-DTFT_CS=-1
;	-DTFT_DC=PIN_LCD_DC
;	-DTFT_RST=PIN_LCD_RST
;	-DLOAD_GLCD=1
;	-DLOAD_FONT2=1
;	-DLOAD_FONT4=1
;	-DSPI_FREQUENCY=27000000
;	-DUSE_HSPI_PORT=1
;	-std=gnu++11

build_flags =
	-Os
	-DCORE_DEBUG_LEVEL=3 ; 0= none, 1= error, 2= warn, 3= info, 4= debug, 5= verbose
	-include include/board_config.hpp
	-Wno-unused-variable
	-Wno-unused-function
	-Wno-narrowing
	-Wno-cpp
	-Werror

